# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
  - contextcheck
  - errcheck
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - typecheck
  - unused
  - whitespace
issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test[.]go
    linters:
      - errcheck
    text: "Error return value of.* is not checked"
  - path: _test[.]go
    linters:
      - gosec
    text: "Potential file inclusion via variable"
  - linters:
    - revive
    # Igorning package comments warning as most our packages don't have package
    # comments.
    text: "package-comments: .*"
linters-settings:
  # https://golangci-lint.run/usage/linters/#linters-configuration
  errcheck:
    check-type-assertions: true
    check-blank: true
