linters:
  disable-all: true
  enable:
  - contextcheck
  - deadcode
  - errcheck
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - whitespace
issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test[.]go
    linters:
      - errcheck
      - gosimple
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
