version: "2"
linters:
  default: none
  enable:
    - contextcheck
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test[.]go
        text: Error return value of.* is not checked
      - linters:
          - gosec
        path: _test[.]go
        text: Potential file inclusion via variable
      - linters:
          - revive
        text: 'package-comments: .*'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
