FROM ghcr.io/crazy-max/docker:20.10.13@sha256:b12c2af335c6a8fa045e81674cd994f1815e56fd0b47ccabf9372db8b61dd05d

RUN apk add --update --no-cache make curl python3

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

ENV PATH=/root/.poetry/bin:$PATH

WORKDIR /tmp/workspace
COPY pyproject.toml ./
RUN poetry install