FROM docker.io/library/ubuntu:20.04@sha256:bea6d19168bbfd6af8d77c2cc3c572114eb5d113e6f422573c93cb605a0e2ffb

RUN \
    apt update && \
    apt-get install -y \
        make \
        docker \
    && true

