version: "3.8"

services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile
      target: "devtools"
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
      - xdg-cache-home:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock:z
    command: ["make", "all"]
    ports:
      - "127.0.0.1:32604:32604"
  hadolint:
    build:
      context: .
      dockerfile: Dockerfile
      target: "hadolint"
    volumes:
      - .hadolint.yaml:/.hadolint.yaml:z
  dockle:
    build:
      context: .
      dockerfile: Dockerfile
      target: "dockle"
    volumes:
      - ./var/oci-images:/srv/images:ro,z
  docker-lock:
    build:
      context: .
      dockerfile: Dockerfile
      target: "docker-lock"
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
volumes:
    xdg-cache-home: {}
