version: "3.8"

services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile
      target: "devtools"
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
      - xdg-cache-home:/root/.cache
      - poetry:/root/.local/share/pypoetry
      - /var/run/docker.sock:/var/run/docker.sock:z
    command: ["make", "all"]
    ports:
      - "127.0.0.1:32604:32604"
  hadolint:
    build:
      context: .
      dockerfile: Dockerfile
      target: "hadolint"
    volumes:
      - .hadolint.yaml:/.hadolint.yaml:z
  dockle:
    build:
      context: .
      dockerfile: Dockerfile
      target: "dockle"
    volumes:
      - ./var/oci-images:/srv/images:ro,z
  docker-lock:
    build:
      context: .
      dockerfile: Dockerfile
      target: "docker-lock"
    working_dir: /srv/workspace
    volumes:
      - .:/srv/workspace:z
  techdocs:
    build:
      context: docker-compose
      dockerfile: Dockerfile
      target: techdocs
    working_dir: /srv/workspace
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT:-}
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
      - $HOME/.config/gcloud:/root/.config/gcloud
      - ${GOOGLE_APPLICATION_CREDENTIALS:-nothing}:${GOOGLE_APPLICATION_CREDENTIALS:-/tmp/empty-GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "127.0.0.1:8000:8000/tcp"
    command: serve
volumes:
  nothing: {}
  poetry: {}
  xdg-cache-home: {}
