version: "3.8"

services:
  devtools:
    build:
      target: "poetry"
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    working_dir: /srv/workspace

volumes:
  xdg-cache-home: { }
