version: "3"
services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /srv/workspace
    volumes:
      - ${WORKSPACE_DIR:-../tests/prototype}:/srv/workspace:z,cached
      - xdg-cache-home:/root/.cache
      - ${HOME}/.argocd:/root/.argocd
volumes:
  xdg-cache-home: {}
