---
version: "3.8"

services:
  pip-tools:
    build:
      context: .
      dockerfile: Dockerfile
      target: "pip-tools"
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    working_dir: /srv/workspace
  npm-tools:
    build:
      context: .
      dockerfile: Dockerfile
      target: "npm-tools"
    volumes:
      - .:/srv/workspace:z
      - ${XDG_CACHE_HOME:-xdg-cache-home}:/root/.cache
    working_dir: /srv/workspace

volumes:
  xdg-cache-home: {}
