on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Override default log level"
        required: false
        default: "debug"
        type: string

  schedule:
    - cron: "0 1-5 * * 1"

jobs:
  renovate:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      issues: write
    uses: coopnorge/github-workflow-renovate/.github/workflows/renovate.yaml@pravindahal/fix/Implement-docker-hub-auth-using-access-token
    secrets: inherit
    with:
      log-level: ${{ inputs.log-level }}
